### ISSUE TITLE
Gestione - Working from home -

### ISSUE THREAD

**Issue by riccardogenova-bitrocketdev** [bitRocket-dev/rocket-cms#364]
Creare un nuovo slice _remoteWorking_ come un oggetto che una un ID generato che è un oggetto TRemoteWorking con _idDeveloper_ _startDate_ _endDate_ _note_ 

Dalla pagina profilo di un Developer deve essere possibile aggiungere un _time remote_ cliccando un bottone all'interno della tab Info. 

Subito sotto il nome, mostrare un testo nel caso in cui nella data odierna lo Sviluppatore lavora in remoto

**Comment by giorgiosangiorgi-bitrocketdev** [comment]
Ciao attendo di visionare il task insieme per considerare i testi corretti da passare alle label. Grazie
